# Generated by Django 2.2 on 2019-05-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.TextField(),
        ),
    ]
