# Generated by Django 2.2 on 2019-05-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190501_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='approve_status',
            field=models.CharField(choices=[('01', 'รอการอนุมัติ'), ('02', 'ไม่อนุมัติ'), ('03', 'อนุมัติ')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='type',
            field=models.CharField(choices=[('01', 'ลากิจ'), ('02', 'ลาป่วย')], max_length=2),
        ),
    ]
